/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-taskmanager-FXUHQpTqbmRJ3-xGCBX-p3I4jwOJh51o",
  "version": "2020-11-20"
}

export default ebconfig;